THISISCVAH-5473: Install the S3 repository plugin on all elasticsearch nodes.
- Plugins should be installed on all nodes in the elasticsearch cluster.
- Ignore the error that tells you a plugin has already been installed.

diff --git a/core/playbooks/roles/elasticsearch/templates/deploy_dip.yml.j2 b/core/playbooks/roles/elasticsearch/templates/deploy_dip.yml.j2
--- a/core/playbooks/roles/elasticsearch/templates/deploy_dip.yml.j2
+++ b/core/playbooks/roles/elasticsearch/templates/deploy_dip.yml.j2
@@ -107,7 +107,24 @@ spec:
             privileged: true
           command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
         - name: install-plugins
-          command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch {{ ' '.join(elasticsearch_plugins) }}']
+          command:
+            - sh
+            - -c
+            - |
+              ERROR=$(bin/elasticsearch-plugin install --batch {{ ' '.join(elasticsearch_plugins) }} 2>&1 > /dev/null)
+              RESULT=$?
+              echo $ERROR | grep -q "already exists"
+              EXISTS=$?
+              if [[ $RESULT -eq 0 || $EXISTS -eq 0 ]]; then
+                echo "Success"
+                echo $RESULT
+                true
+              else
+                echo "Failure"
+                echo $RESULT
+                echo $OUT > /dev/stderr
+                false
+              fi
           env:
           - name: NODE_NAME
             valueFrom:
@@ -177,6 +194,30 @@ spec:
           securityContext:
             privileged: true
           command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
+        - name: install-plugins
+          command:
+            - sh
+            - -c
+            - |
+              ERROR=$(bin/elasticsearch-plugin install --batch {{ ' '.join(elasticsearch_plugins) }} 2>&1 > /dev/null)
+              RESULT=$?
+              echo $ERROR | grep -q "already exists"
+              EXISTS=$?
+              if [[ $RESULT -eq 0 || $EXISTS -eq 0 ]]; then
+                echo "Success"
+                echo $RESULT
+                true
+              else
+                echo "Failure"
+                echo $RESULT
+                echo $OUT > /dev/stderr
+                false
+              fi
+          env:
+          - name: NODE_NAME
+            valueFrom:
+              fieldRef:
+                fieldPath: spec.nodeName
         affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
@@ -234,6 +275,30 @@ spec:
           securityContext:
             privileged: true
           command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
+        - name: install-plugins
+          command:
+            - sh
+            - -c
+            - |
+              ERROR=$(bin/elasticsearch-plugin install --batch {{ ' '.join(elasticsearch_plugins) }} 2>&1 > /dev/null)
+              RESULT=$?
+              echo $ERROR | grep -q "already exists"
+              EXISTS=$?
+              if [[ $RESULT -eq 0 || $EXISTS -eq 0 ]]; then
+                echo "Success"
+                echo $RESULT
+                true
+              else
+                echo "Failure"
+                echo $RESULT
+                echo $OUT > /dev/stderr
+                false
+              fi
+          env:
+          - name: NODE_NAME
+            valueFrom:
+              fieldRef:
+                fieldPath: spec.nodeName
         affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
