(fix) THISISCVAH-13933: Fix commit message linting
- vommit (v0.2 → v1.0.2):
    - gitlint (v0.13.0 → v0.19.1)
- Update .gitlint-docker config file
- Validate THISISCVAH and AFDCO identifiers
- Enforce max body line tab length of 3
- Simplify body line regexp
- Add Closes trailer validation
- Fix tfplenum-bot cherrypicked commit fails
- Minimize docker image size

Issue: https://jira.levelup.cce.af.mil/browse/THISISCVAH-13933

diff --git a/gitlab/commit-lint.yml b/gitlab/commit-lint.yml
--- a/gitlab/commit-lint.yml
+++ b/gitlab/commit-lint.yml
@@ -1,7 +1,7 @@
 Commit Lint:
   stage: commit-lint
   image:
-    name: docker.nexus.sil.lab/tfplenum/vommit:0.2
+    name: $LATEST_VOMMIT_IMAGE
     entrypoint: [""]
   tags:
     - docker-runner
@@ -13,4 +13,4 @@ Commit Lint:
     echo "IP of runner is $(hostname -I | cut -d " " -f1)"
     echo "(script) Current working directory is $(pwd)"
     exit_code=0
-    gitlint --extra-path /root/rules -vv --commit "$CI_COMMIT_SHA" || exit_code=$?; if [ $exit_code -ne 0 ]; then echo -e "\nThe Total Errors: $exit_code\n"; exit 1; else echo -e "GITLINT PASSED\n"; fi;
+    gitlint --config /root/.gitlint-docker --commit "$CI_COMMIT_SHA" || exit_code=$?; if [ $exit_code -ne 0 ]; then echo -e "\nThe Total Errors: $exit_code\n"; exit 1; else echo -e "GITLINT PASSED\n"; fi;
